Repository GSG-G13/ntherapy-express, pull requests merged in 2023-07, with the labels that each got.

#36 [NTH-95] Signup
  package-lock.json
  package.json
  src/config/index.ts
  src/controllers/auth.ts
  src/controllers/index.ts
  src/controllers/s3upload.ts
  src/helpers/nodemailer.ts
  src/helpers/validation/index.ts
  src/helpers/validation/userRegister.ts
  src/routes/auth.ts
  src/routes/index.ts
  src/services/auth.ts
  src/services/index.ts
  src/services/mailBuilder.ts
  src/services/nodemailer.ts
  src/types/index.ts
  src/types/mail.ts
  src/types/therapist.ts
  src/types/user.ts
Labels: awaiting review

#38 [NTH-90] create a route that get user data
  src/controllers/auth.ts
  src/controllers/index.ts
  src/middlewares/checkauth.ts
  src/middlewares/index.ts
  src/routes/auth.ts
Labels: done

#37 Setup Github Action to Check build
  .github/workflows/check-build.yml
Labels: awaiting review, CI/CD

#41 fix: fix userId to therapistId
  src/controllers/auth.ts
  src/helpers/validation/therapist.ts
Labels: bug, done

#42 fix: rename to therapistId search
  src/services/therapists.ts
Labels: awaiting review

#44 [NTH-96] docs: add example .env
  README.md
  example.env
Labels: awaiting review

#46 Fix appointment bug
  __tests__/appointment.ts
  src/controllers/appointment.ts
  src/controllers/auth.ts
Labels: awaiting review

#50 fix: fix /auth when the role is admin
  src/controllers/admin.ts
  src/services/payment.ts
Labels: awaiting review

#52 Price filter
  __tests__/therapists.ts
  src/controllers/therapists.ts
  src/services/therapists.ts
Labels: awaiting review

#51 [NTH-113]fix: fix /auth for admin returning role
  src/controllers/admin.ts
  src/controllers/auth.ts
  src/db/fakeData.ts
  src/models/admin.ts
  src/services/admin.ts
  src/types/models.ts
Labels: awaiting review

#57 feat: create add to github route
  package-lock.json
  package.json
  src/config/index.ts
  src/controllers/bug.ts
  src/controllers/index.ts
  src/routes/bug.ts
  src/services/bug.ts
  src/services/index.ts
Labels: awaiting review
