Repository GSG-G13/ntherapy-express, pull requests merged in 2023-06, with the labels that each got.

#1 feat: Set up project directory structure
  .eslintrc.js
  .gitattributes
  .gitignore
  .vscode/settings.json
  __tests__/index.ts
  jest.config.js
  package-lock.json
  package.json
  src/app.ts
  src/config/index.ts
  src/controllers/index.ts
  src/db/index.ts
  src/helpers/index.ts
  src/helpers/validation/index.ts
  src/index.ts
  src/middlewares/index.ts
  src/models/index.ts
  src/routes/index.ts
  src/services/index.ts
  src/types/index.ts
  tsconfig.json
Labels: awaiting review

#2 Creating Users Table Using Sequelize
  src/config/index.ts
  src/db/buildDB.sql
  src/db/connection.ts
  src/db/index.ts
  src/index.ts
  src/models/index.ts
  src/models/user.ts
  src/types/index.ts
  src/types/models.ts
Labels: changes-requested

#3 feat(api):Create Error Middleware & CustomError helper
  src/app.ts
  src/helpers/CustomError.ts
  src/helpers/index.ts
  src/middlewares/ErrorMiddleware.ts
  src/middlewares/index.ts
Labels: awaiting review

#8 feat(database): create db table Appointments
  .eslintrc.js
  package-lock.json
  src/models/appointment.ts
  src/models/index.ts
  src/models/therapist.ts
  src/types/index.ts
  src/types/models.ts
Labels: changes-requested

#9 feat(database):create session model
  src/models/index.ts
  src/models/session.ts
  src/types/index.ts
  src/types/models.ts
Labels: awaiting review

#10 add cross-env
  package-lock.json
  package.json
  src/config/index.ts
  src/db/buildDB.sql
  src/db/connection.ts
  src/index.ts
Labels: awaiting review

#11 Adding and Fixing Fake Data to the Database
  .vscode/settings.json
  package.json
  src/db/build.ts
  src/db/buildDB.sql
  src/db/connection.ts
  src/db/fakeData.ts
  src/types/models.ts
Labels: awaiting review

#15 [NTH-73] : add Authentication middleware function
  package-lock.json
  package.json
  src/app.ts
  src/config/index.ts
  src/helpers/jwtverify.ts
  src/middlewares/checkauth.ts
  src/middlewares/index.ts
  src/routes/therapist.ts
  src/types/checkauth.ts
  src/types/index.ts
Labels: awaiting review

#13 feat: appointments router with appointmentent controller file appoint…
  __tests__/appointment.ts
  __tests__/index.ts
  package-lock.json
  package.json
  src/controllers/appointment.ts
  src/db/build.ts
  src/helpers/index.ts
  src/helpers/validation/appointments.ts
  src/helpers/validation/index.ts
  src/routes/appointment.ts
  src/routes/index.ts
  src/services/appointment.ts
  src/services/index.ts
Labels: changes-requested

#16 [NTH-75] - Create Google Calendar & Google meet Service
  package-lock.json
  package.json
  src/config/index.ts
  src/services/calendar.ts
  src/types/index.ts
  src/types/therapist.ts
Labels: awaiting review

#17 [NTH-86] update isAvailable
  __tests__/appointment.ts
  src/config/index.ts
  src/controllers/appointment.ts
  src/controllers/index.ts
  src/helpers/index.ts
  src/helpers/validation/appointments.ts
  src/helpers/validation/index.ts
  src/routes/appointment.ts
  src/services/appointment.ts
  src/services/calendar.ts
  src/services/index.ts
Labels: awaiting review

#19 [NTH-74] - feat: nodmailer function added to services file
  src/config/index.ts
  src/services/nodemailer.ts
Labels: awaiting review, changes-requested

#23 [NTH-81] feat: setup github actions
  .github/workflows/delete-cache.yml
  .github/workflows/lint-check.yml
  .github/workflows/test-check.yml
  __tests__/appointment.ts
Labels: awaiting review

#22 [NTH-65] POST appointment
  .github/workflows/test-check.yml
  __tests__/appointment.ts
  src/app.ts
  src/config/constants.ts
  src/controllers/appointment.ts
  src/controllers/index.ts
  src/db/fakeData.ts
  src/helpers/index.ts
  src/helpers/validation/appointments.ts
  src/helpers/validation/index.ts
  src/routes/appointment.ts
  src/services/appointment.ts
  src/services/index.ts
  src/services/therapists.ts
  src/types/index.ts
  src/types/therapist.ts
Labels: awaiting review

#25 [NTH-84] add the total pages to the response
  src/controllers/therapists.ts
  src/services/therapists.ts
Labels: awaiting review

#26 [NTH-67] create BookedAppointment
  .gitignore
  .vscode/settings.json
  __tests__/index.ts
  src/app.ts
  src/controllers/index.ts
  src/controllers/session.ts
  src/routes/index.ts
  src/routes/session.ts
  src/services/index.ts
  src/services/session.ts
  src/types/index.ts
  src/types/therapist.ts
Labels: awaiting review

#24 server to send Client Secret for payment
  package-lock.json
  package.json
  src/app.ts
  src/config/index.ts
  src/controllers/index.ts
  src/controllers/payment.ts
  src/db/fakeData.ts
  src/routes/index.ts
  src/services/index.ts
  src/services/payment.ts
Labels: done

#30 Edit fake data
  src/db/fakeData.ts
  src/models/user.ts
Labels: awaiting review

#28 [NTH-85] Login
  package-lock.json
  package.json
  src/controllers/auth.ts
  src/controllers/index.ts
  src/helpers/index.ts
  src/helpers/jwt.ts
  src/helpers/jwtverify.ts
  src/helpers/validation/index.ts
  src/helpers/validation/userLogin.ts
  src/middlewares/checkauth.ts
  src/routes/auth.ts
  src/routes/index.ts
  src/services/auth.ts
  src/services/index.ts
  src/types/index.ts
  src/types/payload.ts
  src/types/therapist.ts
Labels: changes-requested
